spring:
  application:
    name: hello-spring-cloud-zuul

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: HELLO-SPRING-CLOUD-WEB-ADMIN-RIBBON
    api-b:
      path: /api/b/**
      serviceId: HELLO-SPRING-CLOUD-WEB-ADMIN-FEIGN